---
title: "Join Us"
date: 2020-06-12T12:57:28+08:00
draft: false
---

### Post-doctoral Research Fellowships/Research Fellow

**We are currently seeking highly motivated individuals who share our passion in deciphering the enigma of the brain to join us at the Clinical Brain Lab , Nanyang Technological University! We are seeking candidates interested in educational neuroscience.**

##### **Aim**

We are interested in building capacity for research in the Science of Learning, in particular in the area of educational neuroscience. We seek to understand how cognitive neuroscience can be applied to education to optimize learning. The successful candidate will work closely with researchers at the Centre for Research and Development in Learning (CRADLE), National Institute of Education (NIE), and other international collaborators from institutes such as Johns Hopkins University, Massachusetts Institute of Technology and/or University of Cambridge. The current project will be investigating reading brain networks in bilingual children. Singapore is a multicultural city that has a conducive education system to study this.

##### **Scope**

The main research modalities in our lab include: neuropsychological assessments, cognitive tests, functional Magnetic Resonance (fMRI), diffusion MRI (DTI, HARDI, DSI), electroencephalography (EEG), Transcranial Magnetic Stimulation (TMS).

##### **Who can apply**

We welcome applicants with a doctorate (PhD) degree in various backgrounds such as:
experimental psychology, biopsychology, cognitive psychology, neuropsychology, neurology,
psychiatry, cognitive neuroscience, electrical engineering, medical engineering, computer science, and related fields.

Candidates are expected to have good interpersonal skills and to have demonstrated record of excellent scientific writing skills. Desirable qualification includes one or more of the following

- Experience with conducting behavioral experiments in neuropsychology or cognitive psychology.
- Experience with neuroimaging techniques (MRI/EEG/or TMS).
- Familiarity with image data analysis tools such as SPM, FSL, AFNI, DSIStudio, Matlab, Python etc.

***

To apply, please send Curriculum Vitae, letter of application with research interests, and three letters of recommendation to annabelchen@ntu.edu.sg.

Find out more about [NTU](http://www.ntu.edu.sg) and the [Cognitive Neuroimaging Centre](http://conic.ntu.edu.sg/Pages/default.aspx) (CoNiC) which houses state-of-the-art neuroimaging facilities.
