# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
name = "Home"
url = "#slider"
weight = 10

[[main]]
name = "Research"
url = "#research_theme"
weight = 20

[[main]]
name = "Team"
url = "#people"
weight = 30

[[main]]
name = "Publications"
url = "#publications"
weight = 40

[[main]]
name = "Join Us"
url = "join/"
weight = 75

[[main]]
name = "Participate & Events"
url = "#participate"
weight = 50

[[main]]
name = "Resources & Software"
url = "resources/"
weight = 60

[[main]]
name = "Contact"
url = "#contact"
weight = 80

[[main]]
name = "BrainHack"
url = "brainhack/"
weight = 90

[[join]]
name = "Overview"
url = "/join/#join-cbl-heading"
weight = 10

[[join]]
name = "Graduate Students"
url = "/join/#join-status-heading"
weight = 20

[[join]]
name = "Research Fit"
url = "/join/#join-roles-heading"
weight = 30

[[join]]
name = "Interdisciplinary Brain Science"
url = "/join/#join-ntu-heading"
weight = 40

[[join]]
name = "Get in Touch"
url = "/join/#join-contact-heading"
weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
