---
title: "Join Us"
draft: no
date: '2020-06-12T12:57:28+08:00'
---

### Doctorate Research Fellowship

**We are currently actively recruiting for PhD students interested in developing research in educational neuroscience, affective neuroscience and aging neuroscience (specifically in older neurological patients). These fellowships will be held in the Clinical Brain Laboratory, Division of Psychology, Nanyang Technological University (NTU), Singapore.**

##### **Scope**

Research in the lab is focused on the neural basis of higher cognition in the cerebellum, cognitive training in healthy aging and we will be developing an area in Educational Neuroscience. Main research modalities in our lab include: neuropsychological assessments, cognitive tests, functional Magnetic Resonance (fMRI), diffusion MRI (DTI, HARDI, DSI), EEG and Transcranial Magnetic Stimulation (TMS). The candidate will be expected to conduct research in areas noted above, especially using diffusion MRI. However, he/she is also encouraged to develop own related research topic of interest.

##### **Who can apply**

We welcome applicants with a Bachelors or Masters degree in various backgrounds such as: experimental psychology, biopsychology, cognitive psychology, neuropsychology, neurology, psychiatry, cognitive neuroscience, electrical engineering, medical engineering, computer science, and related fields. The successful applicant will be enrolled in the graduate psychology program by research. For non-local degree holders, GRE exams (general and subject) will be required for application.


*** 

Please address questions or send Curriculum Vita to annabelchen@ntu.edu.sg.

Find out more about our [PhD Programmes](http://admissions.ntu.edu.sg/graduate/R-Programs/Pages/default.aspx)

