---
title: "Join Us"
date: 2020-06-12T12:57:28+08:00
draft: false
---

### Part-time System Administrator

**The Clinical Brain Lab housed within the Division of Psychology at NTU is seeking a part-time system administrator to help with setting up and maintaining networked servers used for image analyses within the lab. The main research focus of the lab is studying brain functions using neuroimaging methods.**

##### **Who can apply**

Graduate or undergraduate students may apply. It is an hourly position or 8-10 hours per week (negotiable). The Clinical Brain Lab is currently involved in various projects in neuroimaging and technological applications in education. The above position would allow acquisition of research experience in this field if the applicant has related interest.


##### **Duties**

- Evaluate and install software packages on behalf of users
- Manage software licenses (E.g. CALs, Matlab etc)
- Ensure QoS and security for servers (Security design and implementation)
- Upgrading and patching server operating systems
- Plan and manage storage life cycle, including backups
- Evaluating software for future deployment
- Troubleshoot any other software and hardware problems
- Website webmaster
- Attend weekly lab meetings
- Communicate with related IT personnel for network issues

##### **Skill Requirements**

- Experience with servers and other high availability appliances
- Managing and configuring network services (E.g. VPN, routing, channel bonding etc.)
- Troubleshooting FlexNET license manager, remote desktop license manager
- Proficiency in RAID and Network file systems (iSCSI LUN, Targets, CIFS)
- Knowledge in web services (Apache, MySQL, FTP)
- Design and implementation of Hypervisors and virtualization (E.g., ESXI, resource pools, virtual switches)
- Matlab, R, C++ and Scripting (Windows PowerShell, or bash/tcsh)
- Familiar with Windows 2008 R2, 2012, CentOS environments.


***

If you have the suitable qualifications and are interested, please send detailed CV and inquiry to annabelchen@ntu.edu.sg.

